// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqpiidlymnpcedndwajr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcGlpZGx5bW5wY2VkbmR3YWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTU3ODQsImV4cCI6MjA3NDI3MTc4NH0.AiLB87FtOYso8CLgQi3NFQZVUbGjyQbOGLckN-9SWxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});